export const providerLogos = {
    'Apple TV': 'https://image.tmdb.org/t/p/original/9ghgSC0MA082EL6HLCW3GalykFD.jpg',
    'Google Play Movies': 'https://image.tmdb.org/t/p/original/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg',
    'Fandango At Home': 'https://image.tmdb.org/t/p/original/19fkcOz0xeUgCVW8tO85uOYnYK9.jpg',
    'Netflix': 'https://image.tmdb.org/t/p/original/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg',
    'Amazon Prime Video': 'https://image.tmdb.org/t/p/original/pvske1MyAoymrs5bguRfVqYiM9a.jpg',
    'Amazon Video': 'https://image.tmdb.org/t/p/original/seGSXajazLMCKGB5hnRCidtjay1.jpg',
    'MUBI': 'https://image.tmdb.org/t/p/original/fj9Y8iIMFUC6952HwxbGixTQPb7.jpg',
    'Hulu': 'https://image.tmdb.org/t/p/original/bxBlRPEPpMVDc4jMhSrTf2339DW.jpg',
    'NetMovies': 'https://image.tmdb.org/t/p/original/jlyafDbXLyNXNNFZbIgB9VrlScW.jpg',
    'maxdome Store': 'https://image.tmdb.org/t/p/original/cBN4jd4wPq6on0kESiTlevqvlnL.jpg',
    'Stan': 'https://image.tmdb.org/t/p/original/sSfxJXq7s8oHf3XWd0FtqagPDsF.jpg',
    'Fandor': 'https://image.tmdb.org/t/p/original/45lSM3J7Ts4TXTtDv0EuTPL0eH5.jpg',
    'Netzkino': 'https://image.tmdb.org/t/p/original/4bKgwiotEIN6wiZNQhQfjp7qPCk.jpg',
    'Sky Go': 'https://image.tmdb.org/t/p/original/kAZkQcIxMxTmlwdgSB05fqtymp0.jpg',
    'WOW': 'https://image.tmdb.org/t/p/original/9r5zFWuYnwjzO1JrNjSbLQwUc3P.jpg',
    'Alleskino': 'https://image.tmdb.org/t/p/original/m0zZQjEHcp8np3lkMdMZE9QRwjA.jpg',
    'MGM Plus': 'https://image.tmdb.org/t/p/original/ctiRpS16dlaTXQBSsiFncMrgWmh.jpg',
    'Rakuten TV': 'https://image.tmdb.org/t/p/original/bZvc9dXrXNly7cA0V4D9pR8yJwm.jpg',
    'BBC iPlayer': 'https://image.tmdb.org/t/p/original/nc8Tpsr8SqCbsTUogPDD06gGzB3.jpg',
    'Now TV': 'https://image.tmdb.org/t/p/original/g0E9h3JAeIwmdvxlT73jiEuxdNj.jpg',
    'ITVX': 'https://image.tmdb.org/t/p/original/1LuvKw01c2KQCt6DqgAgR06H2pT.jpg',
    'Starz': 'https://image.tmdb.org/t/p/original/yIKwylTLP1u8gl84Is7FItpYLGL.jpg',
    'Looke': 'https://image.tmdb.org/t/p/original/9HhIlyFlilVtx0sMTcPbhs5qR31.jpg',
    'BoxOffice': 'https://image.tmdb.org/t/p/original/4JswJbaxqZhut2TpJ3IPUBnNdy8.jpg',
    'ShowMax': 'https://image.tmdb.org/t/p/original/ilR8XFZOr3e3wETQ4ZXLjXQXrts.jpg',
    'Canal VOD': 'https://image.tmdb.org/t/p/original/cAUTwxqoI7zc9XtYr1SMtWZEsXg.jpg',
    'Bbox VOD': 'https://image.tmdb.org/t/p/original/s7mg9n4UHrcdJQL78JmaU6oAdHt.jpg',
    'Orange VOD': 'https://image.tmdb.org/t/p/original/9Fyo6njYvroAIxAzTBbLgnjgYga.jpg',
    'Atres Player': 'https://image.tmdb.org/t/p/original/oN6g8QorcoYo3mx4BulU22ghKq4.jpg',
    'Filmin': 'https://image.tmdb.org/t/p/original/kO2SWXvDCHAquaUuTJBuZkTBAuU.jpg',
    'Filmin Plus': 'https://image.tmdb.org/t/p/original/ozZU2vSlyL11rFGEkq1HE0yxIJq.jpg',
    'Nuestro Cine MX': 'https://image.tmdb.org/t/p/original/aNlqB4iEoh7BQKaKj72iiC4WmkN.jpg',
    'Microsoft Store': 'https://image.tmdb.org/t/p/original/5vfrJQgNe9UnHVgVNAwZTy0Jo9o.jpg',
    'Pathé Thuis': 'https://image.tmdb.org/t/p/original/lnOkJKyFl87mzqNebAbE8ADdHoB.jpg',
    'Videoland': 'https://image.tmdb.org/t/p/original/qN7uDYanT47WI0MmbwOr5HFFot.jpg',
    'Tubi TV': 'https://image.tmdb.org/t/p/original/zLYr7OPvpskMA4S79E3vlCi71iC.jpg',
    'Viaplay': 'https://image.tmdb.org/t/p/original/bnoTnLzz2MAhK3Yc6P9KXe5drIz.jpg',
    'NBC': 'https://image.tmdb.org/t/p/original/6hFf3sIdmXSAczy3i6tLSmy6gwK.jpg',
    'AMC': 'https://image.tmdb.org/t/p/original/92Kx25Od0habmgRBTqT6XWgwgKt.jpg',
    'tenplay': 'https://image.tmdb.org/t/p/original/68wIIGfS8iE1Vk06mAftEnBiFjJ.jpg',
    'The CW': 'https://image.tmdb.org/t/p/original/spcwROYevucLluqZZ8Fv75UuTBt.jpg',
    'U-NEXT': 'https://image.tmdb.org/t/p/original/a5T7vNaGvoeckYO6rQkHolvyYf4.jpg',
    'Acorn TV': 'https://image.tmdb.org/t/p/original/doCc555FPPgGtuaZJxf9QZVpIp5.jpg',
    'Watcha': 'https://image.tmdb.org/t/p/original/5gmEivxOGPdq4Afpq1f8ktLtEW1.jpg',
    'Shudder': 'https://image.tmdb.org/t/p/original/vEtdiYRPRbDCp1Tcn3BEPF1Ni76.jpg',
    'GuideDoc': 'https://image.tmdb.org/t/p/original/eKVmLFHW5PeNhuR7Nedd8OIxW2M.jpg',
    'Channel 4': 'https://image.tmdb.org/t/p/original/uMWCgjsGnO5IoQtqxXOjnQA5gt9.jpg',
    'Timvision': 'https://image.tmdb.org/t/p/original/6FDKQWcR6JfmRKLqezSsvGgRuUY.jpg',
    'Infinity+': 'https://image.tmdb.org/t/p/original/tDlGQeD2LaDaHO62itqblktNwmM.jpg',
    'Ivi': 'https://image.tmdb.org/t/p/original/4smEkH3vlf5V3vo2vwrOQ6Chb35.jpg',
    'Okko': 'https://image.tmdb.org/t/p/original/5z8dpQN27kybhn21EVLZcJPpMEo.jpg',
    'Amediateka': 'https://image.tmdb.org/t/p/original/dNaqCdDy4wsIzjZoYwvLRiOK4Tx.jpg',
    'Kinopoisk': 'https://image.tmdb.org/t/p/original/51wuCkUdkEQTUtB8TrtZzzxp3Tj.jpg',
    'Hotstar': 'https://image.tmdb.org/t/p/original/5B0WB5ohGxRtON8qCuCkGgGCO18.jpg',
    'FXNow': 'https://image.tmdb.org/t/p/original/m4KUe3UoTnLgN4g6txYMnBqeUI5.jpg',
    'Bookmyshow': 'https://image.tmdb.org/t/p/original/hAKPOEwWdjE9evzxByVdF8QUMH3.jpg',
    'Sky Store': 'https://image.tmdb.org/t/p/original/6AKbY2ayaEuH4zKg2prqoVQ9iaY.jpg',
    'SBS On Demand': 'https://image.tmdb.org/t/p/original/cR4okiAS0zcXb4ufs3mi4PImXPB.jpg',
    'Videobuster': 'https://image.tmdb.org/t/p/original/82hFfWsPYtyskBrnkL8Y36vHcVf.jpg',
    'Foxtel Now': 'https://image.tmdb.org/t/p/original/fejdSG7TwNQ5E0p6u7A6LVs280R.jpg',
    'ABC iview': 'https://image.tmdb.org/t/p/original/zR1TJmEwssf0ZThB2iByNtZi2Oo.jpg',
    'FILMO': 'https://image.tmdb.org/t/p/original/br0wtjMDSjMahkhzn5XAXYWyr3V.jpg',
    'Cineplex': 'https://image.tmdb.org/t/p/original/d1mUAhpJpxy0YMjwVOZ4lxAAbeT.jpg',
    'Sundance Now': 'https://image.tmdb.org/t/p/original/1Edma9SrJnqkQW3BqFd2rJNHZvX.jpg',
    'iciTouTV': 'https://image.tmdb.org/t/p/original/7rJJlPpuGz0DV5OLjVW1HzYaFj9.jpg',
    'M6+': 'https://image.tmdb.org/t/p/original/tmYzlEKeiWStvXwC1QdpXIASpN4.jpg',
    'ABC': 'https://image.tmdb.org/t/p/original/aEp5AORtajnh2rc7O33ui8pj2um.jpg',
    'Movistar Plus+ Ficción Total ': 'https://image.tmdb.org/t/p/original/f6TRLB3H4jDpFEZ0z2KWSSvu1SB.jpg',
    'blue TV': 'https://image.tmdb.org/t/p/original/47klot430ytIqldQUUx2avN45Sr.jpg',
    'BritBox': 'https://image.tmdb.org/t/p/original/d2Kx5XtHcd0DBwVwIe7D3X7Sifp.jpg',
    'History': 'https://image.tmdb.org/t/p/original/xqZSzhIcq8qaAU13rMhVhzDi4T8.jpg',
    'Lifetime': 'https://image.tmdb.org/t/p/original/tWq6XvHqPjBW1BZTpf4Nziy8CDD.jpg',
    'Viu': 'https://image.tmdb.org/t/p/original/o7WsYI2r1llIf9h6JTGVX9yTHPx.jpg',
    'Catchplay': 'https://image.tmdb.org/t/p/original/9qSVItdgkVHH3Rrl9db2yRWsgBq.jpg',
    'iflix': 'https://image.tmdb.org/t/p/original/vCTY2WtY1oJ8EKpp0UCz4SRpE4S.jpg',
    'Claro video': 'https://image.tmdb.org/t/p/original/21M5CpiOYGOhHj2sVPXqwt6yeTO.jpg',
    'Netflix Kids': 'https://image.tmdb.org/t/p/original/kwVegvKCinXTPuzZmYT1J3i1HJz.jpg',
    'MagentaTV': 'https://image.tmdb.org/t/p/original/lrEigPPAhggq02q53uM8vdWAIUX.jpg',
    'Hollywood Suite': 'https://image.tmdb.org/t/p/original/dg4Kj9s7N5pZcvJDW6vt5d9j7Uf.jpg',
    'Universal Pictures': 'https://image.tmdb.org/t/p/original/8pvjGOr83RSlPwKfYi6e99mOS4.jpg',
    'Screambox': 'https://image.tmdb.org/t/p/original/x2w49qSgz7bU3o3rENO9Yc11OmC.jpg',
    'Paramount Pictures': 'https://image.tmdb.org/t/p/original/f8zvpzThrDhegtxjQwy74D0jLYr.jpg',
    'YouTube Premium': 'https://image.tmdb.org/t/p/original/rMb93u1tBeErSYLv79zSTR07UdO.jpg',
    'Curzon Home Cinema': 'https://image.tmdb.org/t/p/original/pXQhPQmlIYsIZD4urWs8Ul8PhA6.jpg',
    'Curiosity Stream': 'https://image.tmdb.org/t/p/original/oR1aNm1Qu9jQBkW4VrGPWhqbC3P.jpg',
    'Kanopy': 'https://image.tmdb.org/t/p/original/rcBwnERpNfPfWB5DaSTyEMCZbCA.jpg',
    'YouTube': 'https://image.tmdb.org/t/p/original/pTnn5JwWr4p3pG8H6VrpiQo7Vs0.jpg',
    'AcornTV Amazon Channel': 'https://image.tmdb.org/t/p/original/1wYmvbAuVZz2JnKvYfYN8Qolnb.jpg',
    'BritBox Amazon Channel': 'https://image.tmdb.org/t/p/original/tLBLABfFYYETf9Zk8gKEWnjhMai.jpg',
    'Fandor Amazon Channel': 'https://image.tmdb.org/t/p/original/3eVIcUeRXji5SBV7gEv4f5U4CqV.jpg',
    'MUBI Amazon Channel': 'https://image.tmdb.org/t/p/original/a4IDLKjvP5gvq7tNlg2Xw5YyEkI.jpg',
    'Screambox Amazon Channel': 'https://image.tmdb.org/t/p/original/vmXC3D9Kqtt9TEohDEmcaxnLYA5.jpg',
    'Shudder Amazon Channel': 'https://image.tmdb.org/t/p/original/qb6Lj5BhNJavdmRVDzAqAjd4Tj3.jpg',
    'Sundance Now Amazon Channel': 'https://image.tmdb.org/t/p/original/i8PzzzOVJfXWLE1v5Up7nGTWWhp.jpg',
    'The Roku Channel': 'https://image.tmdb.org/t/p/original/wQzSN83BnWVgO7xEh0SeTVqtrFv.jpg',
    'PBS': 'https://image.tmdb.org/t/p/original/iLjStQKQwzyxXJb3jyNpvDmW9mx.jpg',
    'Sky': 'https://image.tmdb.org/t/p/original/ytApMa9fThUQUFTn696AeNBrB8f.jpg',
    'Freeform': 'https://image.tmdb.org/t/p/original/4cHGd32hhEHmFjDGJcjVEAwFQg0.jpg',
    'Hoopla': 'https://image.tmdb.org/t/p/original/j7D006Uy3UWwZ6G0xH6BMgIWTzH.jpg',
    'ARD Mediathek': 'https://image.tmdb.org/t/p/original/avItehPq07h5nKCJgwNTxl6OD0y.jpg',
    'Rai Play': 'https://image.tmdb.org/t/p/original/cmURKKdS72Ckr52615xvc2JPsJm.jpg',
    'BFI Player': 'https://image.tmdb.org/t/p/original/nIm8xq1JYgHfusIcDnccEBQkoWp.jpg',
    'Crave': 'https://image.tmdb.org/t/p/original/ewOptMVIYcOadMGGJz8DJueH2bH.jpg',
    'Zee5': 'https://image.tmdb.org/t/p/original/vPIW5b0ebTLj9bFCZypoBbF8wSl.jpg',
    'Arte': 'https://image.tmdb.org/t/p/original/vPZrjHe7wvALuwJEXT2kwYLi0gV.jpg',
    'YouTube Free': 'https://image.tmdb.org/t/p/original/4tJBhJcuF1ZstI5Yqu82G0yroLa.jpg',
    'France TV': 'https://image.tmdb.org/t/p/original/maeiT4ORBxykOVlaW9gCsLuFPnS.jpg',
    'Sony Liv': 'https://image.tmdb.org/t/p/original/3973zlBbBXdXxaWqRWzGG2GYxbT.jpg',
    'Universcine': 'https://image.tmdb.org/t/p/original/11Yzww3g6lYZznKrom3cSrKP4St.jpg',
    '7plus': 'https://image.tmdb.org/t/p/original/uU4gqmoX0koF8L5yJSlfaaFd9Tz.jpg',
    'ALLBLK': 'https://image.tmdb.org/t/p/original/4cKdiYEPW1BsWLb9UmNzAyUlD5p.jpg',
    'fuboTV': 'https://image.tmdb.org/t/p/original/9BgaNQRMDvVlji1JBZi6tcfxpKx.jpg',
    'Criterion Channel': 'https://image.tmdb.org/t/p/original/yhrtzYd43pFIhRq0ruO8umJPuyn.jpg',
    'WWE Network': 'https://image.tmdb.org/t/p/original/7Wo1H7YMmRy7S56sz6HJAMYRdGq.jpg',
    'History Vault': 'https://image.tmdb.org/t/p/original/z5jtxEEeJEK1kYDqbyXzfquolC9.jpg',
    'Neon TV': 'https://image.tmdb.org/t/p/original/iscLKFDwQlr0BAgVDBcuRapLiwC.jpg',
    'Pure Flix': 'https://image.tmdb.org/t/p/original/7L4eXQD0yFVDKZ2qwYtxcV5gm6n.jpg',
    'Crunchyroll': 'https://image.tmdb.org/t/p/original/fzN5Jok5Ig1eJ7gyNGoMhnLSCfh.jpg',
    'Lifetime Movie Club': 'https://image.tmdb.org/t/p/original/m4ofXxkTOj04N8df5KJGCIjnWii.jpg',
    'BBC Player Amazon Channel': 'https://image.tmdb.org/t/p/original/jhhFTFVWjKVi2JjDYoqoI4dHsmL.jpg',
    'ZDF Herzkino Amazon Channel': 'https://image.tmdb.org/t/p/original/FtIkEXYkqTxKwCwLK79yKJW8i7.jpg',
    'BFI Player Amazon Channel': 'https://image.tmdb.org/t/p/original/4SJW6thrCvN6ya2hO6naksfRZDF.jpg',
    'Cinemax Amazon Channel': 'https://image.tmdb.org/t/p/original/ohcwolMl8E743CkS8MnhmJKOlRj.jpg',
    'Hallmark+ Amazon Channel': 'https://image.tmdb.org/t/p/original/wVxA3Rw87917VEXChiVKZpXUjSm.jpg',
    'MZ Choice Amazon Channel': 'https://image.tmdb.org/t/p/original/hTAIgvUnmu1Yv0wFVJRu9KKAPtJ.jpg',
    'PBS Kids Amazon Channel': 'https://image.tmdb.org/t/p/original/lIXDKV7LrZfF3SR2m8EQrMVRI5C.jpg',
    'PBS Masterpiece Amazon Channel': 'https://image.tmdb.org/t/p/original/xN1vKpcypShJrWmf1t3dyGJM7sO.jpg',
    'RetroCrush Amazon Channel': 'https://image.tmdb.org/t/p/original/6cQvPAFHDOSq3cXPwcCbh3gCpOi.jpg',
    'Ziggo TV': 'https://image.tmdb.org/t/p/original/ozUfbWZXVdymn8iC3zze0cQPeUi.jpg',
    'RTL+': 'https://image.tmdb.org/t/p/original/jmR0t1kjzHcyV7raynzMbF87J9d.jpg',
    'Pluto TV': 'https://image.tmdb.org/t/p/original/dB8G41Q6tSL5NBisrIeqByfepBc.jpg',
    'Joyn': 'https://image.tmdb.org/t/p/original/tDnDBkSLLLQgFb03J9ttQhZQxZs.jpg',
    'Crave Starz': 'https://image.tmdb.org/t/p/original/csPQMbeJWY7bjwWruZjtc27xf2l.jpg',
    'Globoplay': 'https://image.tmdb.org/t/p/original/7Cg8esVVXOijXAm1f1vrS7jVjcN.jpg',
    'O2 TV': 'https://image.tmdb.org/t/p/original/27yD8cEx7qC1lSzaDvFlW4avXyu.jpg',
    'Sun Nxt': 'https://image.tmdb.org/t/p/original/6KEQzITx2RrCAQt5Nw9WrL1OI8z.jpg',
    'LaCinetek': 'https://image.tmdb.org/t/p/original/1syoSwH2yIskHUqeOiK9re8AMJC.jpg',
    'Be TV Go': 'https://image.tmdb.org/t/p/original/acANFKCTLQuvDPjJAb5SnmzJaT6.jpg',
    'VRT MAX': 'https://image.tmdb.org/t/p/original/gqxv8W54I95K3hNS6UT6sDRe2Az.jpg',
    'CBC Gem': 'https://image.tmdb.org/t/p/original/a7O0Z1uhFjgGydRrgT6ucBisP4K.jpg',
    'Hoichoi': 'https://image.tmdb.org/t/p/original/u7dwMceEbjxd1N3TLEUBILSK2x6.jpg',
    'Alt Balaji': 'https://image.tmdb.org/t/p/original/i7knsL0QgDJyuts5FbfjREUqHvu.jpg',
    'Sky X': 'https://image.tmdb.org/t/p/original/67FAj8KvIiV5iZMJuPUdMrqMftw.jpg',
    'USA Network': 'https://image.tmdb.org/t/p/original/A95qgiMz6ulV2SxeKcJ5Gc9pqGS.jpg',
    'Yle Areena': 'https://image.tmdb.org/t/p/original/nrORhu39C2YjBhx9v8rU8oFlulj.jpg',
    'Cinemas a la Demande': 'https://image.tmdb.org/t/p/original/AboEF9vQyH2AAndLimdO043IzLh.jpg',
    'CTV': 'https://image.tmdb.org/t/p/original/xoFyQOXR3qINRsdnCQyd7jGx8Wo.jpg',
    'FlixFling': 'https://image.tmdb.org/t/p/original/yFGu4sSzwUMfhwmSsZgez8QhaVl.jpg',
    'Fandango at Home Free': 'https://image.tmdb.org/t/p/original/19fkcOz0xeUgCVW8tO85uOYnYK9.jpg',
    'My5': 'https://image.tmdb.org/t/p/original/5qLpN8ah2FZC8NpYFwRFwxlNjRn.jpg',
    'Filmtastic Amazon Channel': 'https://image.tmdb.org/t/p/original/ni0t0Bj4HRAQ9f6zSv1Bl9MDjLK.jpg',
    'Disney Plus': 'https://image.tmdb.org/t/p/original/97yvRBw1GzX7fXprcF80er19ot.jpg',
    'Ruutu': 'https://image.tmdb.org/t/p/original/c7SqVo4DFrbK3RwhGbxvQ9SRco2.jpg',
    'MovistarTV': 'https://image.tmdb.org/t/p/original/tRNA2CRgA4XHvd7Mx9dH3sFtDVb.jpg',
    'blutv': 'https://image.tmdb.org/t/p/original/dqRpKX6vcos334v9huMpNPKHlD8.jpg',
    'puhutv': 'https://image.tmdb.org/t/p/original/ffvIywFtojPQnVwHVmTSZEdemdt.jpg',
    'Bet+ Amazon Channel': 'https://image.tmdb.org/t/p/original/2AvUqoIHAq2lLxRy2IxOBUgCYef.jpg',
    'Rakuten Viki': 'https://image.tmdb.org/t/p/original/5L2bwr9DhUg28oSMEPRCNwB2y7B.jpg',
    'Kino on Demand': 'https://image.tmdb.org/t/p/original/yTwdlHzReo6l9HLWrZqEaEUECBt.jpg',
    'Apple TV+': 'https://image.tmdb.org/t/p/original/2E03IAZsX4ZaUqM7tXlctEPMGWS.jpg',
    'wavve': 'https://image.tmdb.org/t/p/original/hPcjSaWfMwEqXaCMu7Fkb529Dkc.jpg',
    'DocPlay': 'https://image.tmdb.org/t/p/original/pVoZH9ZMGfrr1Ajk1UD29weO6iA.jpg',
    'Mediaset Infinity': 'https://image.tmdb.org/t/p/original/2hBbMVUI2G4GAGRAD0RZCZqDMUh.jpg',
    'NPO Start': 'https://image.tmdb.org/t/p/original/jPNvTunAw7309LeRMT6m3yZy1Lm.jpg',
    'TCM': 'https://image.tmdb.org/t/p/original/8SIxng8eznACvCTRsN1FZfd5Ycg.jpg',
    'TNT': 'https://image.tmdb.org/t/p/original/76CvnJAKAPbJuiXYwQGN7PFqOci.jpg',
    'IndieFlix': 'https://image.tmdb.org/t/p/original/mjsNfr0lswbRx9hbEFkgqJkBjFt.jpg',
    'VOD Club': 'https://image.tmdb.org/t/p/original/y7gH7FKJEE6LrO5h6wZTHQdmukO.jpg',
    'Go3': 'https://image.tmdb.org/t/p/original/1y6ds7KDN5Q33Jb0ZxnroEJ58Gd.jpg',
    '9Now': 'https://image.tmdb.org/t/p/original/xoId9luelz6lXMQkzLyJf3ssXTL.jpg',
    'Canal+': 'https://image.tmdb.org/t/p/original/eBXzkFEupZjKaIKY7zBUaSdCY8I.jpg',
    'TV 2': 'https://image.tmdb.org/t/p/original/ddwrbKxlX8n7TasdvrauFijCmEm.jpg',
    'HBO Max': 'https://image.tmdb.org/t/p/original/b8edpTaLCHFrUnhpGQIZJUpFX7T.jpg',
    'BINGE': 'https://image.tmdb.org/t/p/original/7QX5OdsQZrXGNBKq9SPzoPV9OYQ.jpg',
    'Peacock Premium': 'https://image.tmdb.org/t/p/original/2aGrp1xw3qhwCYvNGAJZPdjfeeX.jpg',
    'Peacock Premium Plus': 'https://image.tmdb.org/t/p/original/drPlq5beqXtBaP7MNs8W616YRhm.jpg',
    'Sooner': 'https://image.tmdb.org/t/p/original/jzWBemDX69VRYhudQA44IESMxQ1.jpg',
    'wedotv': 'https://image.tmdb.org/t/p/original/jAwT86Q0H9U8RESR3zR2FVKe83D.jpg',
    'FlixOlé': 'https://image.tmdb.org/t/p/original/ozMgkAAoi6aDI5ce8KKA2k8TGvB.jpg',
    'TVNZ': 'https://image.tmdb.org/t/p/original/wbqJss5NNebssp5RBkAdxIHecv2.jpg',
    'Film1': 'https://image.tmdb.org/t/p/original/uYJwhSwKHy1BahLwm3KnjP7ajgt.jpg',
    'BBC America': 'https://image.tmdb.org/t/p/original/jfXLhMzHHmBYrtE9ZaW7as2RA98.jpg',
    'Animation Digital Network': 'https://image.tmdb.org/t/p/original/w86FOwg0bbgUSHWWnjOTuEjsUvq.jpg',
    'Here TV': 'https://image.tmdb.org/t/p/original/kiNWL1wGBg3z2FBXJcd8R8MaZrV.jpg',
    'Joyn Plus': 'https://image.tmdb.org/t/p/original/5aHLriu21FRDGlxY5zbzyEuoSvA.jpg',
    'Blockbuster': 'https://image.tmdb.org/t/p/original/auWzottqpExOHUlJwDZ4DvdHGoL.jpg',
    'SF Anytime': 'https://image.tmdb.org/t/p/original/sNmIwrniZZORvNJOmEuWGhwBJNf.jpg',
    'HiDive': 'https://image.tmdb.org/t/p/original/iCV9oPBeoLDC5okFRZEgQkx7je0.jpg',
    'TV 2 Play': 'https://image.tmdb.org/t/p/original/tpfmd22xEapb1aW2gzjSM5104rx.jpg',
    'Flix Premiere': 'https://image.tmdb.org/t/p/original/wCKOLlsilq4I0Iv1NSJTToPEQAo.jpg',
    'OVID': 'https://image.tmdb.org/t/p/original/jxavsObOHN6UqlbuZQ1UpVRVv6X.jpg',
    'OzFlix': 'https://image.tmdb.org/t/p/original/hP3ymMLPyvxUCA1ODfIHJ4pu3c2.jpg',
    'Draken Films': 'https://image.tmdb.org/t/p/original/vyu1bwP7H0p7B8BLB3QRwHVmvlA.jpg',
    'Fetch TV': 'https://image.tmdb.org/t/p/original/9B7l9ZSos54kFrZbliVExt2z9C9.jpg',
    'Hungama Play': 'https://image.tmdb.org/t/p/original/pMTVKAUyjMb0xdMnHqfNj73MGH6.jpg',
    'Chai Flicks': 'https://image.tmdb.org/t/p/original/qesugDq8sUCixmOOsqDM1xAnBYz.jpg',
    'Shout! Factory TV': 'https://image.tmdb.org/t/p/original/y9jFndski0fRO4MHh3yg5PIL9ZI.jpg',
    'ThreeNow': 'https://image.tmdb.org/t/p/original/vcsLhyNRm528LzfVqQJDddusP27.jpg',
    'NFB': 'https://image.tmdb.org/t/p/original/zwTo48JWc9FNCgJ1ADPAfkhYUuA.jpg',
    'NRK TV': 'https://image.tmdb.org/t/p/original/teyfWuW8nS8wsk6rVXIbynrxIX6.jpg',
    'Filmstriben': 'https://image.tmdb.org/t/p/original/eRRc8n7fzQewjh15d2fao45Xxvi.jpg',
    'Dekkoo': 'https://image.tmdb.org/t/p/original/x6nRFzF32hCzMHaVM4RHRo7lsgS.jpg',
    'Retrocrush': 'https://image.tmdb.org/t/p/original/5zUnCq0pvixEtQafzOBBWqxNRvX.jpg',
    'Belas Artes à La Carte': 'https://image.tmdb.org/t/p/original/gBYz3cTgDPRoRFOCS4gG9BNPJdX.jpg',
    'Beamafilm': 'https://image.tmdb.org/t/p/original/mKHumLTIy1SmihWSVqN9iPxFnqf.jpg',
    'Global TV': 'https://image.tmdb.org/t/p/original/o2qiZykonJuLglxwBbtUbHu4wIO.jpg',
    'Picl': 'https://image.tmdb.org/t/p/original/mj1iZQtWmq9s0LmPhZ7KjUtgVja.jpg',
    'RTPplay': 'https://image.tmdb.org/t/p/original/9HQD7iNLyJQYhEq3Z9blyn7P4Vk.jpg',
    'Night Flight Plus': 'https://image.tmdb.org/t/p/original/zOWoxUMmGW0OfDFAQsCosho2PZz.jpg',
    'Mitele ': 'https://image.tmdb.org/t/p/original/273VHxSrDdEwLTXJrsnE6yJMqNZ.jpg',
    'VIX ': 'https://image.tmdb.org/t/p/original/jwRPknT20dfU1GeVqbcDXFyvtdG.jpg',
    'RTBF Auvio': 'https://image.tmdb.org/t/p/original/gdqGg9TIzmQQBmkG8bljY20KX0z.jpg',
    'Kirjastokino': 'https://image.tmdb.org/t/p/original/27Zotk8HAfHk7qPz9x6DWWhOpb7.jpg',
    'Kocowa': 'https://image.tmdb.org/t/p/original/hwsU65QW7A4dbMEWkDpgHyCNcfS.jpg',
    'Bioskop Online': 'https://image.tmdb.org/t/p/original/rvHcdDDyfuFRD2C4mLkTUtKk2CS.jpg',
    'DIRECTV GO': 'https://image.tmdb.org/t/p/original/nr5UBW4IGKgBwmhpTMOfcvnX2vX.jpg',
    'genflix': 'https://image.tmdb.org/t/p/original/o506FcbahVPxvVcsSA5dFLj9drV.jpg',
    'Club Illico': 'https://image.tmdb.org/t/p/original/cQjWvOiKRPeSuWRNGegcBjyqVbR.jpg',
    'NLZIET': 'https://image.tmdb.org/t/p/original/88ssxWDyhabjrwSrbSf87nCDK2y.jpg',
    'Revry': 'https://image.tmdb.org/t/p/original/llQ8zV50Wqh4gYCYfr52R1b9gfD.jpg',
    'ShemarooMe': 'https://image.tmdb.org/t/p/original/ec3kgfQ6YXbT3AFRh8bkQZQFLb2.jpg',
    'DOCSVILLE': 'https://image.tmdb.org/t/p/original/5zqbck5mo8PuVbGu2ngBUdn5Yga.jpg',
    'EPIC ON': 'https://image.tmdb.org/t/p/original/ymlo2k6RlX0zF5Te1AYwXRQ7Pra.jpg',
    'GOSPEL PLAY': 'https://image.tmdb.org/t/p/original/vPqYxDMMtoHlYg8ZzEXS5S6y6iQ.jpg',
    'Home of Horror': 'https://image.tmdb.org/t/p/original/ntvIffmJe7ZO1SSobwSx8ABAZFG.jpg',
    'Filmtastic': 'https://image.tmdb.org/t/p/original/eptSSZPhXJllBI8QywFDmgOMNkU.jpg',
    'ArthouseCNMA': 'https://image.tmdb.org/t/p/original/eBt8WXNGuJGBgQ28W88Y3eTAWsD.jpg',
    'ManoramaMax': 'https://image.tmdb.org/t/p/original/tFkqZYsDhNe6hJCx50Aw6oma24w.jpg',
    'MAX Stream': 'https://image.tmdb.org/t/p/original/zDSJn28xTG4f6h2yxZ6UmCPvZ8j.jpg',
    'Claro tv+': 'https://image.tmdb.org/t/p/original/7EpFKOCMrlo3bjsyBMrec64c7Wb.jpg',
    'Spectrum On Demand': 'https://image.tmdb.org/t/p/original/aAb9CUHjFe9Y3O57qnrJH0KOF1B.jpg',
    'tvo': 'https://image.tmdb.org/t/p/original/yQhSfwOzTF9EATdq47LlRFghmiO.jpg',
    'Vidio': 'https://image.tmdb.org/t/p/original/l2ZNwMC37iK0fquVuYWfcgIJJdF.jpg',
    'CINE': 'https://image.tmdb.org/t/p/original/21uSo4VQUdEmeA6RJ6gPSRwusbt.jpg',
    'SVT': 'https://image.tmdb.org/t/p/original/oBdaG066fB5O7XYrYKQflOZvd89.jpg',
    'Cineasterna': 'https://image.tmdb.org/t/p/original/w1V9hzBaRlkpISBWhCv676kI8Mp.jpg',
    'Tele2 Play': 'https://image.tmdb.org/t/p/original/jy4yvY3szonb0p6rtMXvF5stuX9.jpg',
    'Oldflix': 'https://image.tmdb.org/t/p/original/rXNXvz2096ri69ZlZsFwKxZYJsS.jpg',
    'Tata Play': 'https://image.tmdb.org/t/p/original/5VLMQDq6LWfftQCl7sYrtTseXRA.jpg',
    'Hi-YAH': 'https://image.tmdb.org/t/p/original/pPoqVHcko7XoCRrPus4boDW90uM.jpg',
    'Player': 'https://image.tmdb.org/t/p/original/jhMNVBV2UocEGepRkr9oFPD7Gpb.jpg',
    'TBS': 'https://image.tmdb.org/t/p/original/cZvP3XsDKlHFhNIyHYCVPStXT5l.jpg',
    'tru TV': 'https://image.tmdb.org/t/p/original/mMJ6AQUpHDsD5s2Q2dnbpX1NFwp.jpg',
    'DisneyNOW': 'https://image.tmdb.org/t/p/original/d8HzRaIa5aGE5mJB1SsIA9hODdx.jpg',
    'Discovery+': 'https://image.tmdb.org/t/p/original/bPW3J8KlLrot95sLzadnpzVe61f.jpg',
    'iWantTFC': 'https://image.tmdb.org/t/p/original/nHxedyutqerk1yWBsc17mF8gteZ.jpg',
    'Shadowz': 'https://image.tmdb.org/t/p/original/qwRq7klF8EijYs7XgvxSaYd6v6w.jpg',
    'AsianCrush': 'https://image.tmdb.org/t/p/original/jCgWMxqGaq0h0VOxyJPfQdTqmii.jpg',
    'MX Player': 'https://image.tmdb.org/t/p/original/ayHY6wKxvCKj2PU8eRPFxnPc6B0.jpg',
    'Noovo': 'https://image.tmdb.org/t/p/original/ss6JfWLwwrIjO1AfEsBy8GYM1EU.jpg',
    'TriArt Play': 'https://image.tmdb.org/t/p/original/sgws7qaFHYTEeYhc8RCjZ5D7IlH.jpg',
    'Popcorntimes': 'https://image.tmdb.org/t/p/original/3kmmwlTET45ryW7azWfFJ0Piwll.jpg',
    'Knowledge Network': 'https://image.tmdb.org/t/p/original/7wADjxAylhGGqWYNz86jGOQSoZG.jpg',
    'AMC+': 'https://image.tmdb.org/t/p/original/ovmu6uot1XVvsemM2dDySXLiX57.jpg',
    'AMC+ Amazon Channel': 'https://image.tmdb.org/t/p/original/2ino0WmHA4GROB7NYKzT6PGqLcb.jpg',
    'ARROW': 'https://image.tmdb.org/t/p/original/wAuMUrRTVaJ2CZ4ZpyQbayZx0iU.jpg',
    'Paramount Plus': 'https://image.tmdb.org/t/p/original/h5DcR0J2EESLitnhR8xLG1QymTE.jpg',
    'aha': 'https://image.tmdb.org/t/p/original/8WerMI8XcZXqPpkHTZNtzMzousF.jpg',
    'Amazon Arthaus Channel': 'https://image.tmdb.org/t/p/original/9MABvFilVMUAV86vLUgBgeM5LQQ.jpg',
    'Argo': 'https://image.tmdb.org/t/p/original/jQMOpRluniNQSEp6V7IvtKxXMW.jpg',
    'ZDF': 'https://image.tmdb.org/t/p/original/ugus0p8BGGhE8sxhwAjJz2o8jyy.jpg',
    'Plex': 'https://image.tmdb.org/t/p/original/vLZKlXUNDcZR7ilvfY9Wr9k80FZ.jpg',
    'Viddla': 'https://image.tmdb.org/t/p/original/zDWv7ROPCqZXsIKSVFRANOTC1wx.jpg',
    'Elisa Viihde': 'https://image.tmdb.org/t/p/original/eglAxQEXSO13p6gNf3HKymrIu7y.jpg',
    'rtve': 'https://image.tmdb.org/t/p/original/3QQKYFUDt13Q2Zm6JM2cOjlbd27.jpg',
    'filmfriend': 'https://image.tmdb.org/t/p/original/zXu75uIAMgdblYvFFPzoIHmQhxa.jpg',
    'Libreflix': 'https://image.tmdb.org/t/p/original/3MsEoFiBy9eaUdKo5Cx1iR9BPQy.jpg',
    'WOW Presents Plus': 'https://image.tmdb.org/t/p/original/6dET59jNU0ADysghEjl8Unuc7Ca.jpg',
    'IFFR Unleashed': 'https://image.tmdb.org/t/p/original/fpHXCUD89WRC21wJjz3DDCgyudw.jpg',
    'Tenk': 'https://image.tmdb.org/t/p/original/7up8PVB6RaL0fDs5XFzjJlq9mg2.jpg',
    'Magellan TV': 'https://image.tmdb.org/t/p/original/mSH24WQcRDJ2fsL5iucXqqRnSRb.jpg',
    'QFT Player': 'https://image.tmdb.org/t/p/original/fFIAM3bHNoyjeQ8q160NWUD3S94.jpg',
    'Telia Play': 'https://image.tmdb.org/t/p/original/7QzLA6rsML2rKxhuagWlDl7Zxlm.jpg',
    'BroadwayHD': 'https://image.tmdb.org/t/p/original/6IYZ4NjwPikxN7J9cfSmuyeHeMm.jpg',
    'More TV': 'https://image.tmdb.org/t/p/original/yyMxS08v80D96O7NtL9supa5sn7.jpg',
    'Filmzie': 'https://image.tmdb.org/t/p/original/eUBxtrqO26wAJfYOZJOzhQEo3mm.jpg',
    'Filmoteket': 'https://image.tmdb.org/t/p/original/rTLyVzy9lyPpujUQ026CiRDqQrF.jpg',
    'Lionsgate Play': 'https://image.tmdb.org/t/p/original/e2hCUg2Z3sJ6yWF9NLU24SIKeWa.jpg',
    'MovieSaints': 'https://image.tmdb.org/t/p/original/9vMVMnVnWwxt0TkCazKLYW1zuqY.jpg',
    'KPN': 'https://image.tmdb.org/t/p/original/nzjqsR28PVVp5GJAlHtbBArNKqN.jpg',
    'True Story': 'https://image.tmdb.org/t/p/original/aRPDQvVcpeY07sjI6lAALMCL0ti.jpg',
    'DocAlliance Films': 'https://image.tmdb.org/t/p/original/vbXJBJVv3u3YWt6ml0l0ldDblXT.jpg',
    'Premier': 'https://image.tmdb.org/t/p/original/r7cgAhlSLI4r80P1Si9P0jOevrr.jpg',
    'RTL Play': 'https://image.tmdb.org/t/p/original/3KaY2AQFkPHlc6QgGQmRbYxnsQa.jpg',
    'OnDemandKorea': 'https://image.tmdb.org/t/p/original/gR8rrj71VCLjlF1LJpplo72MXf0.jpg',
    'KlikFilm': 'https://image.tmdb.org/t/p/original/f1V0OhsOKnOQVyNb8h8BbioorQ4.jpg',
    'TvIgle': 'https://image.tmdb.org/t/p/original/3EJQtj4m83kRh7bV9BF6KWmPiKp.jpg',
    'Strim': 'https://image.tmdb.org/t/p/original/3ZigBD8WTEPcEHAvMWiJGUsv5u4.jpg',
    'Film Movement Plus': 'https://image.tmdb.org/t/p/original/8cjvUhc1ga7ySEdAFM7Ok9G6HOr.jpg',
    'Nova Play': 'https://image.tmdb.org/t/p/original/ApcuSS6VOCV7slF4GBRARfy31bg.jpg',
    'iQIYI': 'https://image.tmdb.org/t/p/original/c4eVkfMna2VzHzZ8N2vWXUnMrlD.jpg',
    'Paramount+ Amazon Channel': 'https://image.tmdb.org/t/p/original/hExO4PtimLIYn3kBOrzsejNv7cT.jpg',
    'MGM+ Amazon Channel': 'https://image.tmdb.org/t/p/original/efu1Cqc63XrPBoreYnf2mn0Nizj.jpg',
    'Discovery+ Amazon Channel': 'https://image.tmdb.org/t/p/original/lgudHqEtTOzkMWlpTjU1oUyoUSZ.jpg',
    'Metrograph': 'https://image.tmdb.org/t/p/original/q4WTdA5wH3TXDFiYKejCCwSOyJ8.jpg',
    'IFC Amazon Channel': 'https://image.tmdb.org/t/p/original/tw81Wj2gaVL30O7CvzfsqTLMxQg.jpg',
    'MGM Amazon Channel': 'https://image.tmdb.org/t/p/original/ny55kYI31jrwSYp2LmCniMCGc03.jpg',
    'TELETOON+ Amazon Channel': 'https://image.tmdb.org/t/p/original/4KZlGfHQEza2dBf3HVk4oWmh611.jpg',
    'Now TV Cinema': 'https://image.tmdb.org/t/p/original/6sJLsWk4TZHz1EffmTRSkaDehkh.jpg',
    'STV Player': 'https://image.tmdb.org/t/p/original/aG4lXRDfHl3qgQCgpWI6KEJV0i7.jpg',
    'Eros Now Amazon Channel': 'https://image.tmdb.org/t/p/original/6xQrNQoTmXWhaJj4O8u2FRsXBXs.jpg',
    'Arrow Video Amazon Channel': 'https://image.tmdb.org/t/p/original/u4OSH6NN7bdHRJJVLwozPa0jDUj.jpg',
    'Full Moon Amazon Channel': 'https://image.tmdb.org/t/p/original/xIu1EW7y2EC7RD3Wqe0Ogi5NAuo.jpg',
    'Pokémon Amazon Channel': 'https://image.tmdb.org/t/p/original/l4h4b2esfTb7evLRiLrMjk6rsHj.jpg',
    'Shout! Factory Amazon Channel': 'https://image.tmdb.org/t/p/original/ivRp15loTWoVy3eEHALoYEyXI8J.jpg',
    'FilmBox Live Amazon Channel': 'https://image.tmdb.org/t/p/original/xJ3B83btVmp4wyRGRRRgWCibTLI.jpg',
    'CuriosityStream Amazon Channel': 'https://image.tmdb.org/t/p/original/tLbUhvK1RcA5I4JHndxf5dprkE7.jpg',
    'DocuBay Amazon Channel': 'https://image.tmdb.org/t/p/original/91oRDZySWtw60ei006uQ45gmjXD.jpg',
    'Super Channel Amazon Channel': 'https://image.tmdb.org/t/p/original/5W6vTKE684EhdITeMUjdcTIBGdh.jpg',
    'StackTV Amazon Channel': 'https://image.tmdb.org/t/p/original/djTJ7pAkIhmPaN3eTA6wTUrphNG.jpg',
    'OUTtv Amazon Channel': 'https://image.tmdb.org/t/p/original/d0KmcInHpiF44ahOLrXCQATEFmD.jpg',
    'Love Nature Amazon Channel': 'https://image.tmdb.org/t/p/original/bSy9zFiZtbKBHIyOu0H2Fs5cJmx.jpg',
    'Smithsonian Channel Amazon Channel': 'https://image.tmdb.org/t/p/original/bEgGGEDgBczZcZRJ6x1MtTym2LV.jpg',
    'BBC Earth Amazon Channel': 'https://image.tmdb.org/t/p/original/2WEzLLWbvMLHSNkAjYrIeDOmLJM.jpg',
    'ALLWAYSBLK Amazon Channel': 'https://image.tmdb.org/t/p/original/srLngtBaRGooYsVgkvzkGCwbZHA.jpg',
    'Amazon Prime Video Free with Ads': 'https://image.tmdb.org/t/p/original/gZlCYHPx9a0TRUCEeTvHXBf9ibX.jpg',
    'VI movies and tv': 'https://image.tmdb.org/t/p/original/1tCAM3WVOl0xknuwVc0v1LBWZNV.jpg',
    'W4free': 'https://image.tmdb.org/t/p/original/sSMxh3tIOAi3QBoSXdagDxb3OKp.jpg',
    'DRTV': 'https://image.tmdb.org/t/p/original/dnD5cUeAPruAcYwwKKxYbMcfccq.jpg',
    'Nordisk Film+': 'https://image.tmdb.org/t/p/original/dB6eeNS5TEykyQLPixHOPQqzPcp.jpg',
    'UPC TV': 'https://image.tmdb.org/t/p/original/l5SFTF3l9l1KSgZJM7foAppUenz.jpg',
    'WeTV': 'https://image.tmdb.org/t/p/original/r3tmJFjecQGAfHjWOafhr1pux6b.jpg',
    'KKTV': 'https://image.tmdb.org/t/p/original/r9rEesXJjzY8sH3NLqNdkPdZ714.jpg',
    'LINE TV': 'https://image.tmdb.org/t/p/original/j35eayHG7RC9Ll0ehtbOuek0TZL.jpg',
    'Otta': 'https://image.tmdb.org/t/p/original/z7IYTxUHSrk1VPYgsc5RDe1E3tA.jpg',
    'Voyo': 'https://image.tmdb.org/t/p/original/iTzW2q9e1Kk10l2s934SDgPSJNm.jpg',
    'Edisonline': 'https://image.tmdb.org/t/p/original/hsuv1uc7SUr9YjCXRlLQNELt4UU.jpg',
    'OSN': 'https://image.tmdb.org/t/p/original/kC6JTo59Gj6I4vJPyBAYGh0sKAE.jpg',
    'STARZPLAY': 'https://image.tmdb.org/t/p/original/pDroY6RxYdVw63eAepag4b116Ub.jpg',
    'HRTi': 'https://image.tmdb.org/t/p/original/yHqa57jOQqhBarOh9lw2noJno00.jpg',
    'Paramount+ Roku Premium Channel': 'https://image.tmdb.org/t/p/original/ywIoxSjoYJGUIbR6BfxUiCHdPi3.jpg',
    'Starz Roku Premium Channel': 'https://image.tmdb.org/t/p/original/9laPF1MAiUxlqM8T98F3Gj0bhzd.jpg',
    'AMC+ Roku Premium Channel': 'https://image.tmdb.org/t/p/original/gAGrSQCTAisxy2CsWbijVvJEnRo.jpg',
    'MGM Plus Roku Premium Channel': 'https://image.tmdb.org/t/p/original/lD7HKUmXDvUya58DceiTA809Zbf.jpg',
    'Pickbox NOW': 'https://image.tmdb.org/t/p/original/p6hKVngF1iWciIyxYmrl3UUitg7.jpg',
    'Public Domain Movies': 'https://image.tmdb.org/t/p/original/aN0Y2BNZQBH91JkVOeLTs8IhQrH.jpg',
    'CineMember': 'https://image.tmdb.org/t/p/original/6vchFMhgi7jhyXyKBoutzwMmM5b.jpg',
    'Nexo Plus': 'https://image.tmdb.org/t/p/original/jyiwuXdyRrh2R5UwY4MhOF4Xbfy.jpg',
    'STUDIOCANAL PRESENTS Apple TV Channel': 'https://image.tmdb.org/t/p/original/48aHN85OncgXjtl6DOVOJ6Wni4g.jpg',
    'Eventive': 'https://image.tmdb.org/t/p/original/fwx5Ed64TkfWiRH1SOSkc4781Ts.jpg',
    'Filmlegenden Amazon Channel': 'https://image.tmdb.org/t/p/original/iM7Ed1d7mYT3DQWSqLoW3tIN4uS.jpg',
    'Cinema of Hearts Amazon Channel': 'https://image.tmdb.org/t/p/original/coWnECpOyKLWMTSlXkfT2PhLs9E.jpg',
    'Bloody Movies Amazon Channel': 'https://image.tmdb.org/t/p/original/jG5tKt6JoHsYRoUq6Wg8i9QuHt2.jpg',
    'Film Total Amazon Channel': 'https://image.tmdb.org/t/p/original/3fhcb4cThixkfNpOudnpLcosTCA.jpg',
    'Looke Amazon Channel': 'https://image.tmdb.org/t/p/original/xht0G3uRLcTgjxRz3cDHuf8KKUw.jpg',
    'FlixOlé Amazon Channel': 'https://image.tmdb.org/t/p/original/2GQVxfaiWA4n93I7sJDJf1b6NqS.jpg',
    'Cine+ OCS Amazon Channel ': 'https://image.tmdb.org/t/p/original/4LnuoJ2E5nTWCvXnlGFaUNH324v.jpg',
    'Home of Horror Amazon Channel': 'https://image.tmdb.org/t/p/original/7Zy6GqC8lQEvfBlWC1bJcaJzPRd.jpg',
    'Arthouse CNMA Amazon Channel': 'https://image.tmdb.org/t/p/original/tnQ5PGryncrVxE9bK6nxif82wtd.jpg',
    'ShortsTV Amazon Channel': 'https://image.tmdb.org/t/p/original/2nFBw1zMzN1AujFaCsmsgSKWdfS.jpg',
    'TVCortos Amazon Channel': 'https://image.tmdb.org/t/p/original/32R4lsqOPclNhb3qV613J8T8mdL.jpg',
    'Pongalo Amazon Channel  ': 'https://image.tmdb.org/t/p/original/t7I2Tx6Q7Nz96KexIPjkzUJOCbt.jpg',
    'Play Suisse': 'https://image.tmdb.org/t/p/original/c1Nj8YGitlXbvvv0taHLkBeyTaK.jpg',
    'Cultpix': 'https://image.tmdb.org/t/p/original/uauVx3dGWt0GICqdMCBYJObd3Mo.jpg',
    'Turk On Video Amazon Channel': 'https://image.tmdb.org/t/p/original/9aLd9gAK6xHtWK2tXDYq1fOqzJA.jpg',
    'Serially': 'https://image.tmdb.org/t/p/original/911zAHHLswJYihv988hbHDKa5M4.jpg',
    'meJane': 'https://image.tmdb.org/t/p/original/651I5dLHpxDUePZcNkYTDcARTeE.jpg',
    'FilmBox+': 'https://image.tmdb.org/t/p/original/fbveJTcro9Xw2KuPIIoPPePHiwy.jpg',
    'iBAKATV': 'https://image.tmdb.org/t/p/original/k1LBSLQ2d6B95VpMoBASkM7EdZ2.jpg',
    'IROKOTV': 'https://image.tmdb.org/t/p/original/4bsFc5AgxDNdDeS1NIjVRviARhB.jpg',
    'Hollywood Suite Amazon Channel': 'https://image.tmdb.org/t/p/original/29VK28jsSjFWHdXl1lxPb2SGmAk.jpg',
    'Moviedome Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/9NYihXY9biyXFJSZQq5HIGu1n8B.jpg',
    'Aniverse Amazon Channel': 'https://image.tmdb.org/t/p/original/a2wCZ9ultzAbjAaG6JMiCFJoy9s.jpg',
    'Superfresh Amazon Channel': 'https://image.tmdb.org/t/p/original/9T5H28SXBkzmnZYy2iRfI7GzwLL.jpg',
    'Comedy Central Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/eMoqH13BYzIC1wDlhONhHfDM3DN.jpg',
    'BluTV Amazon Channel': 'https://image.tmdb.org/t/p/original/AvUM6aAqYh7JxUokb5T5ERn3KMs.jpg',
    'GRJNGO Amazon Channel': 'https://image.tmdb.org/t/p/original/cYzZyot2IuGUYUXLvw6BMBT6v9p.jpg',
    'MTV Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/g06QZd5k4bjDEcZ3J97jb3rNlfB.jpg',
    'RTL Passion Amazon Channel': 'https://image.tmdb.org/t/p/original/gHBdFYhxdeLHl8jimTDwA1bFv01.jpg',
    'Silverline Amazon Channel': 'https://image.tmdb.org/t/p/original/xXN970tHrMfL7BQUTVSu96IY9gs.jpg',
    'Shahid VIP': 'https://image.tmdb.org/t/p/original/7qZED0kLBtiV8mLRNBtW4PQCAqW.jpg',
    'Acontra Plus': 'https://image.tmdb.org/t/p/original/8vES2nJNwOF57muvqLByDLm6snp.jpg',
    'ESPN': 'https://image.tmdb.org/t/p/original/ymuWlPllUC1TYw36qjsmia0XqJ8.jpg',
    'AVA VOBB': 'https://image.tmdb.org/t/p/original/nJlTOUfDEUD6fQLopWBnUNzo2NA.jpg',
    'AVA HBZ': 'https://image.tmdb.org/t/p/original/p1mlqlIOtPPZf7lckxX3XLAm2ia.jpg',
    'AVA CSAL': 'https://image.tmdb.org/t/p/original/aqyyZxc2tQ1gEORXNF2d55GvD5P.jpg',
    'AVA BGB': 'https://image.tmdb.org/t/p/original/zJtYNzq9lpMrsqhg6t2y9AWs9dL.jpg',
    'Infinity Selection Amazon Channel': 'https://image.tmdb.org/t/p/original/q77DpszIupURiKGDeFdSHo7TsTF.jpg',
    'CG Collection Amazon channel': 'https://image.tmdb.org/t/p/original/9bRB5nKmQPZYGQkUtLRhw1w0IcD.jpg',
    'iWonder Full Amazon channel': 'https://image.tmdb.org/t/p/original/iZzlUo191ynXNpPNdcY8vvlYSf6.jpg',
    'Full Action Amazon Channel': 'https://image.tmdb.org/t/p/original/xdUXTl4ontqdKv9ZpSBZKiOTyWm.jpg',
    'Cine Comico Amazon Channel': 'https://image.tmdb.org/t/p/original/gQoeIu88CiTF54vYRGwTONHEAtO.jpg',
    'Universcine Amazon Channel': 'https://image.tmdb.org/t/p/original/uPhMKOrup9jtJHIci8FXo3D6y5x.jpg',
    'Action Max Amazon Channel': 'https://image.tmdb.org/t/p/original/1PhTUiq01Z82nvuJlDNYtBnRRN0.jpg',
    'Filmo Amazon Channel': 'https://image.tmdb.org/t/p/original/4clLD3X9nTapdRey1FgcSUPYRy3.jpg',
    'Insomnia Amazon Channel': 'https://image.tmdb.org/t/p/original/nJ43DUei5yK9wWG3g9YpYT4UfN4.jpg',
    'Shadowz Amazon Channel': 'https://image.tmdb.org/t/p/original/vBbNBDZnpnhgHe5ZO9CVur4DmkG.jpg',
    'INA  madelen Amazon Channel': 'https://image.tmdb.org/t/p/original/zg1uFDzIchkwrwOW6dq7LFxB4n6.jpg',
    'Benshi Amazon Channel': 'https://image.tmdb.org/t/p/original/yXSOt0AKxG28wXhnBaogQGwF7Rq.jpg',
    'Planet Horror Amazon Channel': 'https://image.tmdb.org/t/p/original/yISpVXhf6axqiHh6lBvJ8RRrZ8v.jpg',
    'Dizi Amazon Channel': 'https://image.tmdb.org/t/p/original/tM1HabyA45cnckBEhLS7hAVga5g.jpg',
    'Acontra Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/tGvAD4O9obFP3DfOrDn8NaRQ6eT.jpg',
    'Historia y Actualidad Amazon Channel': 'https://image.tmdb.org/t/p/original/aJECXkHekrkuRZ7ABF5YR9DVDd8.jpg',
    'Icon Film Amazon Channel': 'https://image.tmdb.org/t/p/original/jTtwvCgQxD8W7vljH5pH28PfYQD.jpg',
    'Curzon Amazon Channel': 'https://image.tmdb.org/t/p/original/kSONYxM7a0mESEjCaqaozVTdByB.jpg',
    'Hallmark TV Amazon Channel': 'https://image.tmdb.org/t/p/original/x2cjJAyU8CLwyYHaIxzzEjXJFU8.jpg',
    'Studiocanal Presents Amazon Channel': 'https://image.tmdb.org/t/p/original/mLif0L2p0M2AK4pbqHOBqLwB3bP.jpg',
    'TOD': 'https://image.tmdb.org/t/p/original/bFxDjHDXP02u1dLPZfTsTC1L6EA.jpg',
    'TF1+': 'https://image.tmdb.org/t/p/original/blrBF9R2ONYu04ifGkYEb3k779N.jpg',
    'filmingo': 'https://image.tmdb.org/t/p/original/704tOH9qi7y7DDl1CmzDCAI0dcQ.jpg',
    'Sooner Amazon Channel': 'https://image.tmdb.org/t/p/original/6WQqJyaFd0fmLLE6WIjFQyEyAFj.jpg',
    'Bet+': 'https://image.tmdb.org/t/p/original/biHGb84xAzYrNkdvX5XWQTmgzC8.jpg',
    'Yorck on Demand': 'https://image.tmdb.org/t/p/original/zHjoZOQ2DOlu2HCZH18bzQYGc3t.jpg',
    'ESPN Plus': 'https://image.tmdb.org/t/p/original/kYOixe7a3Vg5o6DG1i2S9MMK640.jpg',
    'Paramount+ with Showtime': 'https://image.tmdb.org/t/p/original/kkUHFtdjasnnOknZN69TbZ2fCTh.jpg',
    'Takflix': 'https://image.tmdb.org/t/p/original/ed0vz5bryWIhQB5sHiuGvHKnHHn.jpg',
    'SkyShowtime': 'https://image.tmdb.org/t/p/original/gQbqEYd0C9uprYxEUqTM589qn8g.jpg',
    'Love and Passion Amazon Channel': 'https://image.tmdb.org/t/p/original/rYszOzWFzq7xPffwJ7XN5rJRI7u.jpg',
    'Klassiki': 'https://image.tmdb.org/t/p/original/ehLnHewfxeKWCL7PT5K4AzTXIcV.jpg',
    'Starz Amazon Channel': 'https://image.tmdb.org/t/p/original/esiLBRzDUwodjfN8gA4qj7l3ZF7.jpg',
    'Netflix basic with Ads': 'https://image.tmdb.org/t/p/original/kICQccvOh8AIBMHGkBXJ047xeHN.jpg',
    'Studiocanal Presents MOVIECULT Amazon Channel': 'https://image.tmdb.org/t/p/original/3VYyCBiG2WTCZ2tGzTkWvoXTeqi.jpg',
    'Studiocanal Presents ALLSTARS Amazon Channel': 'https://image.tmdb.org/t/p/original/tHX1KI8VdAzKWMxSgPKqKfHcxFA.jpg',
    'Cohen Media Amazon Channel': 'https://image.tmdb.org/t/p/original/QAtDmj6XHlkPvw5xAjF08ZQARh.jpg',
    'Max Amazon Channel': 'https://image.tmdb.org/t/p/original/erfmV26akboHUerxGjpl8pBwww3.jpg',
    'TOD TV': 'https://image.tmdb.org/t/p/original/gaDNJ1xISHBBq9LQXwwe8PPSRHD.jpg',
    'Behind the Tree': 'https://image.tmdb.org/t/p/original/fxYgfnsrUWa7e9aNr3j3RERpm66.jpg',
    'Popflick': 'https://image.tmdb.org/t/p/original/f5yNbaK23OSWV5IocAj8FZwIOQj.jpg',
    'Tivify': 'https://image.tmdb.org/t/p/original/8VhN4PeHU7yfMNoWK0DnwdS1HlS.jpg',
    'Britbox Apple TV Channel ': 'https://image.tmdb.org/t/p/original/xp12VXTZfunk568CAPs2Xqknimq.jpg',
    'Paramount Plus Apple TV Channel ': 'https://image.tmdb.org/t/p/original/tJqmTmQ8jp9WfyaZfApHK8lSywA.jpg',
    'AMC Plus Apple TV Channel ': 'https://image.tmdb.org/t/p/original/oTQdXIqM9iewlN4MC2nhKB0gHw.jpg',
    'Starz Apple TV Channel': 'https://image.tmdb.org/t/p/original/1C5EVCWyQD798CE1DFfcm6oAbxP.jpg',
    'Magenta TV': 'https://image.tmdb.org/t/p/original/f195E2gXoZBp7QjGNL4XICXxiDk.jpg',
    'Telenet': 'https://image.tmdb.org/t/p/original/kwftIxtjuCAROIcdd53UEjzSmca.jpg',
    'Univer Video': 'https://image.tmdb.org/t/p/original/44E23wCM3WLsvAVRyk6fye76cZb.jpg',
    'Filmow': 'https://image.tmdb.org/t/p/original/oHr80zlf3DWxF6imu6QKqcz275.jpg',
    'ViX Premium Amazon Channel': 'https://image.tmdb.org/t/p/original/6S6kGNEmB4iSq83FX2zWTz8aLMN.jpg',
    'Runtime': 'https://image.tmdb.org/t/p/original/oJRCAz1WKkKM9Ge7mX5KFnegTNY.jpg',
    'TVING': 'https://image.tmdb.org/t/p/original/qHThQdkJuROK0k5QTCrknaNukWe.jpg',
    'BrutX Amazon Channel': 'https://image.tmdb.org/t/p/original/2HsZxiwKi9Ym91r6WY9ojORvq79.jpg',
    'Animation Digital Network Amazon Channel': 'https://image.tmdb.org/t/p/original/9jmtFeqCWvTSYpMMUPNhk8JNJWS.jpg',
    'Universal+ Amazon Channel': 'https://image.tmdb.org/t/p/original/4ABGBjAMtRrYUrr0w3QfanuiaoB.jpg',
    'alleskino Amazon Channel': 'https://image.tmdb.org/t/p/original/s7ZjSKXOtjKBb7hAzBm3b0iY0SG.jpg',
    'RTL Crime Amazon Channel': 'https://image.tmdb.org/t/p/original/5Qe65kN95Z0CytOaG3I8bytdW7A.jpg',
    'CineAutore Amazon Channel': 'https://image.tmdb.org/t/p/original/vM8Oe43bljZqRenO2xSIRHT7GMN.jpg',
    'Anime Generation Amazon Channel': 'https://image.tmdb.org/t/p/original/xcXI50PQIBsRDAP6eEpv09Vz8SG.jpg',
    'Raro Video Amazon Channel': 'https://image.tmdb.org/t/p/original/vXXpcM5yoD8GBWi6U50dOiKgukH.jpg',
    'MIDNIGHT FACTORY Amazon Channel': 'https://image.tmdb.org/t/p/original/sL8ViH6zWOe07xHoiwxUwCXy890.jpg',
    'Amazon MX Player': 'https://image.tmdb.org/t/p/original/yfIWD2zJNHla5RD4xjQNzvKMEwP.jpg',
    'Max': 'https://image.tmdb.org/t/p/original/fksCUZ9QDWZMUwL2LgMtLckROUN.jpg',
    'ARD Plus': 'https://image.tmdb.org/t/p/original/qTybjmHLNcXZExZLBnm4muVCDzP.jpg',
    'TV+': 'https://image.tmdb.org/t/p/original/c8ryDZroFQtuyRVPBwXq5PLpTWV.jpg',
    'Apollo': 'https://image.tmdb.org/t/p/original/5FeLH5VGqpE4K48huk2T5h2xnY5.jpg',
    'Reserva Imovision': 'https://image.tmdb.org/t/p/original/cV6ShEHGS1Bs83xszJlorJVRU47.jpg',
    'Prima Plus': 'https://image.tmdb.org/t/p/original/vrefjVylvD4RkEjQguuXebCp9UQ.jpg',
    'Filmtastic bei Canal+': 'https://image.tmdb.org/t/p/original/kP741xlbpymqjELaTcPiAet3SnV.jpg',
    'Lepsi TV': 'https://image.tmdb.org/t/p/original/489t5n9o1KhH7voGNQkrXT7vBKV.jpg',
    'TV4 Play': 'https://image.tmdb.org/t/p/original/5lKPs5yrjeKHFrXh9RIvzyJJzSd.jpg',
    'Reveel': 'https://image.tmdb.org/t/p/original/en3dbHAWzDpvDhsI0G8LphUhpBr.jpg',
    'ServusTV On': 'https://image.tmdb.org/t/p/original/kVUNXh1Rt9JnwCDotghBKEwLGdH.jpg',
    'Angel Studios': 'https://image.tmdb.org/t/p/original/znTpq1dy5TYxm1QLoxORzuOuwYq.jpg',
    'Cineverse': 'https://image.tmdb.org/t/p/original/jpEV1w3CnrpDQ1vRvGQIZF1S6vA.jpg',
    'AD tv': 'https://image.tmdb.org/t/p/original/mK8nfCXfwoAa6cAkHUSKCkLEIKK.jpg',
    'Midnight Pulp': 'https://image.tmdb.org/t/p/original/8s4adSGz4UmVOP5uegNkoikSFLV.jpg',
    'Allente': 'https://image.tmdb.org/t/p/original/a6z85DKGuPOyTg03TlJ6ShzzFO6.jpg',
    'Xumo Play': 'https://image.tmdb.org/t/p/original/xfKqqWYYIyvjECOFOaYtJdD7gl3.jpg',
    'National Geographic': 'https://image.tmdb.org/t/p/original/nlOrX8YVYjxFkEpfvJHayNg9UAB.jpg',
    'Molotov TV': 'https://image.tmdb.org/t/p/original/8qSG9LtUhBQIWy2Fr6fzeW7gBdd.jpg',
    'Crunchyroll Amazon Channel': 'https://image.tmdb.org/t/p/original/pgjz7bzfBq4nFDu8JJDLBoUVAX8.jpg',
    'DistroTV': 'https://image.tmdb.org/t/p/original/6gdKp9OwHgDLloethSPxZbtovkl.jpg',
    'myfilmfriend': 'https://image.tmdb.org/t/p/original/mWAOUnJY6hnQghUZpjuDB815efG.jpg',
    'Filmicca': 'https://image.tmdb.org/t/p/original/ptNJnBKMVLv3XxmLU9UMVSDop80.jpg',
    'Outside Watch': 'https://image.tmdb.org/t/p/original/jLD5zHgsAhSWBRTnMUOLaXrUuVI.jpg',
    'NPO Plus': 'https://image.tmdb.org/t/p/original/cYyxWlMG0o1dKRvOdpMrVIFrY4F.jpg',
    'Brollie': 'https://image.tmdb.org/t/p/original/zlOChFXWhfIqK2QCf6KPxu0nH2D.jpg',
    'ZDF Select Amazon Channel ': 'https://image.tmdb.org/t/p/original/mmDWKHiDLmHDo2OWnduQuI1T4bh.jpg',
    'GlewedTV': 'https://image.tmdb.org/t/p/original/pr64iEnZZ3qjsUqWS39R5JC97CX.jpg',
    'Videoload': 'https://image.tmdb.org/t/p/original/dKh2TJ9lTWV0UIcDQGMnMyQ8AIN.jpg',
    'TELE 5': 'https://image.tmdb.org/t/p/original/a1zZJiOid4gG27xJtkcDaSVrQdb.jpg',
    'MTV Katsomo': 'https://image.tmdb.org/t/p/original/wRMEDOZ8iAEEHXIY2VyckvT0K8I.jpg',
    'A&E Crime Central Apple TV Channel': 'https://image.tmdb.org/t/p/original/a0vfnBfWPAF6OtKZCzlyiW9A9l6.jpg',
    'Acorn TV Apple TV': 'https://image.tmdb.org/t/p/original/kx8rGgFYxX6aJkG7RHx2mtijglC.jpg',
    'ALLBLK Apple TV channel': 'https://image.tmdb.org/t/p/original/voNwdFHk9uc2ZEWKZlwSQDsfRJN.jpg',
    'ARD Plus Apple TV channel': 'https://image.tmdb.org/t/p/original/9jxvmD363A04nuMw9jgyLzeDB3J.jpg',
    'Arthaus+ Apple TV channel': 'https://image.tmdb.org/t/p/original/as1NArQkfAnptYQP3VS03GOJPdm.jpg',
    'BET+  Apple TV channel': 'https://image.tmdb.org/t/p/original/yFk3WffvGGUtIjJBSV0pgsciaEB.jpg',
    'BFI Player Apple TV Channel': 'https://image.tmdb.org/t/p/original/kohVS01u3sP5IkqsSaAKdBit6aP.jpg',
    'Carnegie Hall+ Apple TV Channel': 'https://image.tmdb.org/t/p/original/dDHyeNrfnloy6skW0j6oIUXFa3Z.jpg',
    'OUTtv Apple TV Channel': 'https://image.tmdb.org/t/p/original/1SuB6tXdKaW4qDRDiqm9C1nr1mD.jpg',
    'UP Faith & Family Apple TV Channel': 'https://image.tmdb.org/t/p/original/92iY4soQNVzNM02mHGjqovPdzdF.jpg',
    'Tastemade Apple TV Channel': 'https://image.tmdb.org/t/p/original/5a0E4ozONnF8rw5cI3n9uueK9WM.jpg',
    'Sundance Now Apple TV Channel': 'https://image.tmdb.org/t/p/original/1x0LxXHUibIolT5fxdSamGGMBC3.jpg',
    'Shudder Apple TV Channel': 'https://image.tmdb.org/t/p/original/kLfq0I2MwiUFUY9yI1GwOeKxX8f.jpg',
    'ScreenPix Apple TV Channel': 'https://image.tmdb.org/t/p/original/96HJkA4nMkcOtiqH9oF1YYtGBHK.jpg',
    'Love Nature Apple TV Channel': 'https://image.tmdb.org/t/p/original/dy9XKHyf16dSB1Lg7KIrtUwDxIX.jpg',
    'Lionsgate Play Apple TV Channel': 'https://image.tmdb.org/t/p/original/p8i1zUcZYQ7qU6RrGvGbDItvcx4.jpg',
    'Lifetime Play Apple TV Channel': 'https://image.tmdb.org/t/p/original/hwX55ugBE1qtM62egayb1CHvNEh.jpg',
    'Lifetime Movie Club Apple TV Channel': 'https://image.tmdb.org/t/p/original/cpSQ9P0ntzr1gZcxHIyaryihpgH.jpg',
    'IFC Films Unlimited Apple TV Channel': 'https://image.tmdb.org/t/p/original/tPvmybuDUn84aDps72GiMbvr2xU.jpg',
    'HISTORY Vault Apple TV Channel': 'https://image.tmdb.org/t/p/original/fsert5S2L3CWSFyaAODiWPOScmz.jpg',
    'Hallmark+ Apple TV Channel': 'https://image.tmdb.org/t/p/original/hGIjvx8BIK4sHZwRYyyB17Pfywj.jpg',
    'Eros Now Select Apple TV Channel': 'https://image.tmdb.org/t/p/original/cqgeSQHqKEkfcmsiy7GoCnf1Q2I.jpg',
    'CuriosityStream Apple TV Channel': 'https://image.tmdb.org/t/p/original/z9x1xFFKjHTYlLYWtiPhAjN4jOp.jpg',
    'Cinemax Apple TV Channel': 'https://image.tmdb.org/t/p/original/zXCdY4pczONheFCU9GkrMbGI1o5.jpg',
    'ALLBLK Amazon channel ': 'https://image.tmdb.org/t/p/original/dj9jb4fiaHILc5GtF76BXzrsGZj.jpg',
    'ARD Plus Amazon channel ': 'https://image.tmdb.org/t/p/original/aiRdDAPESgu9ztDFcLtrSqFa0W2.jpg',
    'Carnegie Hall+ Amazon Channel': 'https://image.tmdb.org/t/p/original/xT5I4zZ2XTLhOVA5ooQIsqjSC3R.jpg',
    'HISTORY Vault Amazon Channel': 'https://image.tmdb.org/t/p/original/fr8lHD0EAYU01UIhg6u8kJrk7jQ.jpg',
    'Lionsgate Play Amazon Channel': 'https://image.tmdb.org/t/p/original/yVbjPWEbsStanRAxwKMDARVOvsn.jpg',
    'Lifetime Play Amazon Channel': 'https://image.tmdb.org/t/p/original/zNYEUs0Z5t7jJqnLTtla8v6AoS4.jpg',
    'Wedo TV': 'https://image.tmdb.org/t/p/original/ptSF973yIl90KwhEmNWDvN1nhan.jpg',
    'Plex Channel': 'https://image.tmdb.org/t/p/original/27WMfRN7pQE3j5Khm8fPM7vYyLV.jpg',
    'Troma NOW': 'https://image.tmdb.org/t/p/original/2CYF8CNs5WK3sB69K0AlmwUxrzv.jpg',
    'KiKA': 'https://image.tmdb.org/t/p/original/5JkLub6H7HsWyLHbitnuXTzXmlJ.jpg',
    'Lifetime Movie Club Amazon Channel': 'https://image.tmdb.org/t/p/original/bKWKqZYT3wrpq1Lyi2qSmx1qlqh.jpg',
    'Amazon Prime Video with Ads': 'https://image.tmdb.org/t/p/original/8aBqoNeGGr0oSA85iopgNZUOTOc.jpg',
    'Canal+ online': 'https://image.tmdb.org/t/p/original/hMfeG5pus99eh1xrSaC2r7YG5vw.jpg',
    'Premiery Canal+': 'https://image.tmdb.org/t/p/original/mBliLuM0AbkRPGDoVa7IGxwC59b.jpg',
    'Adrenalina Pura Amazon channel': 'https://image.tmdb.org/t/p/original/5lcKyzjIFl9ur2Nk8YsXd5kR7vc.jpg',
    'Adrenalina Pura Apple TV channel': 'https://image.tmdb.org/t/p/original/ctse3rS9jiPiOvDwBEFtpVUOnnq.jpg',
    'Far East Amazon Channel ': 'https://image.tmdb.org/t/p/original/5kpTR2iwaoBk9AkPZvlfgeYvbsv.jpg',
    'Cinu': 'https://image.tmdb.org/t/p/original/twKkyl31iYVtxfICNkDdrxrJ7KS.jpg',
    'BYUtv': 'https://image.tmdb.org/t/p/original/9YYuvhTfMuBR7keJ7DPa1GFlDrF.jpg',
    'AXN Black Amazon Channel': 'https://image.tmdb.org/t/p/original/bh0e83QEvjzttsj8FJcQaYxPR43.jpg',
    'Kino Film Collection': 'https://image.tmdb.org/t/p/original/l8nPh3HtqfIJiFTYT7RdNdsv1XD.jpg',
    'Arthaus+': 'https://image.tmdb.org/t/p/original/inTlUMvnQrtCee5fnO4J45SuIwH.jpg',
    'MGM Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/efu1Cqc63XrPBoreYnf2mn0Nizj.jpg',
    'MGM+ Apple TV Channel': 'https://image.tmdb.org/t/p/original/foWKiK4ikpdM72OGN2B8jjyy6OY.jpg',
    'CG tv': 'https://image.tmdb.org/t/p/original/aRy3fDxHOKRq3nhC5J4Sp96kW2b.jpg',
    'ORF ON': 'https://image.tmdb.org/t/p/original/d1d8EljUNvWVU09ShQyXHE1mO9L.jpg',
    'ORF KIDS': 'https://image.tmdb.org/t/p/original/5fS4WiQZ7yX3fBHKelQBO9NwUcD.jpg',
    'Telecine Amazon Channel': 'https://image.tmdb.org/t/p/original/9kcTsX2laYclN4bFiMH3RuhZel2.jpg',
    'Reserva Imovision Amazon Channel': 'https://image.tmdb.org/t/p/original/rvepVasXaE7VFNNXR9pm0tGMu97.jpg',
    'Stingray Amazon Channel': 'https://image.tmdb.org/t/p/original/eUOFD3Vr0BSV6IfBzUEYLozFXNk.jpg',
    'CurtaOn Amazon Channel': 'https://image.tmdb.org/t/p/original/lerdRkZ4vwe4gEZfSxpDpLF4uVl.jpg',
    'Sony One Amazon Channel': 'https://image.tmdb.org/t/p/original/b4vLoTkxvsjOB9kG2V0jsczRl1Q.jpg',
    'Atresplayer Amazon Channel': 'https://image.tmdb.org/t/p/original/7lF4oJgbweKKeb9PemMUAw86ji2.jpg',
    'Vix Gratis Amazon Channel': 'https://image.tmdb.org/t/p/original/iHQ9I6iKiIAHSg4sAztp9QGYSs4.jpg',
    'Gaia Amazon Channel': 'https://image.tmdb.org/t/p/original/7SOOyT9PP0DMdsCXESdfMqbrFKW.jpg',
    'Cindie Amazon Channel': 'https://image.tmdb.org/t/p/original/3Urtm9N9KL9cvhHBAKMpROdee1n.jpg',
    'DocPlay Amazon Channel': 'https://image.tmdb.org/t/p/original/qLT8rsghGQ92bsC0PAKtu4JAjTX.jpg',
    'Iwonder Amazon Channel': 'https://image.tmdb.org/t/p/original/3sOfrPDIomU45q0EN4Z9jQ3OfeG.jpg',
    'Rialto Amazon Channel': 'https://image.tmdb.org/t/p/original/cgdnToW3i10CWEoSoQC6Zq9mO9H.jpg',
    'Anime Digital Network Amazon Channel': 'https://image.tmdb.org/t/p/original/h5QpXIpSnvrPFnOLRXV83CtVHQH.jpg',
    'Strand Releasing Amazon Channel': 'https://image.tmdb.org/t/p/original/jUgtBLZzpaLVTNnqGYDOU9BlCzU.jpg',
    'Hoichoi Amazon Channel': 'https://image.tmdb.org/t/p/original/8ipK9EjNHvcPM22SgqKdA8wZjal.jpg',
    'ManoramaMAX Amazon Channel': 'https://image.tmdb.org/t/p/original/fY2J5CojsKC52LO2K8P5AQAH2UT.jpg',
    'Chaupal Amazon Channel': 'https://image.tmdb.org/t/p/original/sOikKxPVWnwUqa46nt8SwrQ53ui.jpg',
    'BBC Kids Amazon Channel': 'https://image.tmdb.org/t/p/original/vAlwpM4ey2gRvgWmg5mHrjOAIU4.jpg',
    'Sony Pictures Amazon Channel': 'https://image.tmdb.org/t/p/original/i7FaDWpD2xoIWB5lyF191cykfck.jpg',
    'Vrott Amazon Channel': 'https://image.tmdb.org/t/p/original/3LH55fdW1UrjDITGZcJlQT4wRqB.jpg',
    'Anime Times Amazon Channel': 'https://image.tmdb.org/t/p/original/p2fVhnzr0znG2KnVLmH9bjj7F0S.jpg',
    'NammaFlix Amazon Channel': 'https://image.tmdb.org/t/p/original/8WPLg0mQQUdzWZw7xDaM0POmwfO.jpg',
    'Plaion Pictures': 'https://image.tmdb.org/t/p/original/sElRjek77o2yGbiFizqPbjLdyra.jpg',
    'Toggo': 'https://image.tmdb.org/t/p/original/745WQrNUjgJfUXxM2OJAoFkPhsw.jpg',
    'Kixi': 'https://image.tmdb.org/t/p/original/jASACep2h6gPgTEfilfsn0mFteF.jpg',
    'Verleihshop': 'https://image.tmdb.org/t/p/original/4JfSo3RoLuGtvY3jyjaVtxcwp2A.jpg',
    'Freenet meinVOD': 'https://image.tmdb.org/t/p/original/xo4zowa5gbKT4z65ZathH6H4Cdg.jpg',
    '3sat': 'https://image.tmdb.org/t/p/original/mvI5xXSRCBkPlcq83CI21rEMuGk.jpg',
    'CDA Premium': 'https://image.tmdb.org/t/p/original/rZG2UBzS8ysl2kloSbrm9w4Mth2.jpg',
    'Akibapass': 'https://image.tmdb.org/t/p/original/eeu878U02fXr6ef3OfeiVVUS8yv.jpg',
    'NFL Game Pass Amazon Channel': 'https://image.tmdb.org/t/p/original/1vj24IM8I6CMqB95aTKEg3I8hhP.jpg',
    'Disaster X Amazon Channel': 'https://image.tmdb.org/t/p/original/a688PNhEgWvLPzxr7AgAD8pDfE9.jpg',
    'Galactic Stream Amazon Channel': 'https://image.tmdb.org/t/p/original/yRtZJF9vKrSSwwsgUS6XycBdAl0.jpg',
    'BATTLEZONE Amazon Channel': 'https://image.tmdb.org/t/p/original/59jxqvvHok2RxWZ4gsdNs33be5r.jpg',
    'tabii': 'https://image.tmdb.org/t/p/original/uWVpt3iJ2pLKtFZ69rAKP0EDVVx.jpg',
    '3Cat': 'https://image.tmdb.org/t/p/original/lDvzuBuNVgpcdzDpPmmufKvrZPb.jpg',
    'FlixHouse': 'https://image.tmdb.org/t/p/original/69eoIMVggmpyY7Aa8qeN4jsREfd.jpg',
    'Movistar Plus+': 'https://image.tmdb.org/t/p/original/jse4MOi92Jgetym7nbXFZZBI6LK.jpg',
    'Apple TV Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/yFrZVSC4UnDpeIzX2svcRPgV5P5.jpg',
    'ASIATIC Amazon Channel': 'https://image.tmdb.org/t/p/original/kZkxB1p2hAo5TDYBxiPB087VcDq.jpg',
    'Auto Motor und Sport Amazon Channel': 'https://image.tmdb.org/t/p/original/kdK7YNtuILiP8eczeXV9nv6w6rd.jpg',
    ' AXN White Amazon Channel ': 'https://image.tmdb.org/t/p/original/fA2DzD3tCoGt3LLCfH2N4K9klQi.jpg',
    'Fix And Foxi Amazon Channel': 'https://image.tmdb.org/t/p/original/hj3dCuFVj4iBRQsYHRVtVGZ8ezb.jpg',
    'FlimmerkisteTV Amazon Channel': 'https://image.tmdb.org/t/p/original/kuDPlNYeBXdJdBS1VhbwWEKXf8t.jpg',
    'Franatic Amazon Channel': 'https://image.tmdb.org/t/p/original/cvh6xn93xim49GzNEwxx43CHRiS.jpg',
    'GEO Television Amazon Channel': 'https://image.tmdb.org/t/p/original/xc1sNY9m26IWTDLVch4l5RITE5n.jpg',
    'GEO Wild Amazon Channel': 'https://image.tmdb.org/t/p/original/15d0DEceQYOTdUhbTV4h90MCwzw.jpg',
    'Good Movies Amazon Channel': 'https://image.tmdb.org/t/p/original/qPnVZlOKd5UnoE7cZzjM9Bnmry5.jpg',
    'Gute Laune TV Amazon Channel': 'https://image.tmdb.org/t/p/original/4fvNDhHvuFLhd0kYDneFw11exxO.jpg',
    'Historama Amazon Channel': 'https://image.tmdb.org/t/p/original/j0EdO7R89IKdVkOE7jG4UnlJWJx.jpg',
    'Kabel Eins Classics Amazon Channel': 'https://image.tmdb.org/t/p/original/4H9Cr9iKiKwJkjBqJn4TgHu3ufL.jpg',
    'Kinderwelt Amazon Channel': 'https://image.tmdb.org/t/p/original/6rUYLv7HEvx5DK1D6MQXy3MkLQc.jpg',
    'Kixi Select Amazon Channel': 'https://image.tmdb.org/t/p/original/2ixS9fp8UgxGifDn9aNxyeMyShc.jpg',
    'Moconomy Amazon Channel': 'https://image.tmdb.org/t/p/original/AeebTPbgU6JeJ2OkptaFjeCsmvQ.jpg',
    'Netzkino Select Amazon Channel': 'https://image.tmdb.org/t/p/original/ge0PnSsdq9tCFY7UVpPwVKddaER.jpg',
    'Okidoki Amazon Channel': 'https://image.tmdb.org/t/p/original/fNrfISilqgSKJPPrYFmVBwzQm0x.jpg',
    'ProSieben Fun Amazon Channel': 'https://image.tmdb.org/t/p/original/uP1H33OCslvhtlFzYTicmHivq9O.jpg',
    'Qello Concerts by Stingray Amazon Channel': 'https://image.tmdb.org/t/p/original/nRNX3ijGNhKfX9av9wDZK9SUYsq.jpg',
    'Queer Cinemab Amazon Channel': 'https://image.tmdb.org/t/p/original/kMfIUfVymOKnLwQGBAAUl6V8Q6H.jpg',
    'RTL Living Amazon Channel': 'https://image.tmdb.org/t/p/original/mv5q5cRD3SwijtJQ13lktAo1Zow.jpg',
    'Sat.1 emotions Amazon Channel': 'https://image.tmdb.org/t/p/original/eOHPreGr7UvOGMEpVqXWZdcJAiT.jpg',
    'Spiegel Geschichte Amazon Channel': 'https://image.tmdb.org/t/p/original/f3RXdwfzEfl5tf68T4Z1e78RT5Y.jpg',
    'Sportdigital Amazon Channel': 'https://image.tmdb.org/t/p/original/jZbW29NXgiM8jWH9GQ1yqGdeUTA.jpg',
    'Stingray Classica Amazon Channel': 'https://image.tmdb.org/t/p/original/ycsoT2ziFng88zD2bIPLkHPICdj.jpg',
    'Stingray Djazz Amazon Channel': 'https://image.tmdb.org/t/p/original/n9DgrL43vTO4BAOrPzvfeVnIhFS.jpg',
    'Stingray Karaoke Amazon Channel': 'https://image.tmdb.org/t/p/original/hhrxkhGheXYIxySqg4RcvO4tywc.jpg',
    'Terra X Amazon Channel': 'https://image.tmdb.org/t/p/original/orskeNGDTbM3Ja0XdJL6GsBsJux.jpg',
    'TV1000 Russian Kino Amazon Channel': 'https://image.tmdb.org/t/p/original/oJzhATqCZWDMaJTSymuYzHPYGz8.jpg',
    'Waidwerk Amazon Channel': 'https://image.tmdb.org/t/p/original/3iD98wKWhYod5mon6doUoSuHaZP.jpg',
    'Wild West Amzon Channel': 'https://image.tmdb.org/t/p/original/wjIZsNyJ3BtYURWZoBzMSUQYjvg.jpg',
    'Monomax': 'https://image.tmdb.org/t/p/original/kwuUSaCoI9XN0ofHGVTkRm4BMYt.jpg',
    'Max UNext Channel': 'https://image.tmdb.org/t/p/original/cT8C7KjGlmaLrcsXkZhQpRhqpQs.jpg',
    'JustWatchTV': 'https://image.tmdb.org/t/p/original/uCMLyl8jGIbInVyDeCeV6kpciFm.jpg',
    'VIVA by videofutur': 'https://image.tmdb.org/t/p/original/PAaj5bekwbeeoRC1evWg4KJW8p.jpg',
    'Adrenalin Amazon channel': 'https://image.tmdb.org/t/p/original/35u6ZIq0zht35nkeo5W1X9AmbIK.jpg',
    'Allstars Amazon Channel': 'https://image.tmdb.org/t/p/original/8fE593wjaked3UDNEb0Aw9WsSNW.jpg',
    'Fernsehen mit Herz Amazon Channel': 'https://image.tmdb.org/t/p/original/4zKrTkGhbh1KjFksg3gVPsZiPt2.jpg',
    'Moviecult Amazon Channel': 'https://image.tmdb.org/t/p/original/1egNE9hIti4LGeVJPGHbgXuXXO9.jpg',
    'Redlight Cinema Amazon Channel': 'https://image.tmdb.org/t/p/original/3ImESY1OFx7UC7fBwakvjSEmra5.jpg',
    'Seven Entertainment Amazon Channel': 'https://image.tmdb.org/t/p/original/91mdl623RUIlQGr3ZlbB6uxKM9W.jpg',
    'Stingray All good vibes Amazon Channel': 'https://image.tmdb.org/t/p/original/4xHQUeeZAptdMlzTRuZAFyE61DV.jpg',
    'Thrillbox Amazon Channel': 'https://image.tmdb.org/t/p/original/Qq3ZiMvLl288BvhVoBv8lFot8I.jpg',
    'Viaplay Amazon Channel': 'https://image.tmdb.org/t/p/original/sElGn8Ml7yYKuAsceZYQ0nKpqHa.jpg',
    'ZDF Krimi Amazon Channel': 'https://image.tmdb.org/t/p/original/r3Ure9Slzgn6hcjMQKVIgf0ORBV.jpg',
    'ZDFtivi Amazon channel': 'https://image.tmdb.org/t/p/original/8w42AXYRf7BiaRMsFTUCsTSuz63.jpg',
    'Bergblick Amazon Channel': 'https://image.tmdb.org/t/p/original/txD7jP7uZCsfoYkkCrJ20RgW2R0.jpg',
    'ITVX Premium': 'https://image.tmdb.org/t/p/original/1LuvKw01c2KQCt6DqgAgR06H2pT.jpg',
    'Mercado Play': 'https://image.tmdb.org/t/p/original/yGXdJGI6K2fPhpUoCt22yjLkgRj.jpg',
    'Paramount Plus Premium': 'https://image.tmdb.org/t/p/original/h5DcR0J2EESLitnhR8xLG1QymTE.jpg',
    'Paramount Plus Basic with Ads': 'https://image.tmdb.org/t/p/original/rl6zez5rCeyelt1I46JRYk6B9Ed.jpg',
    'Premiere Max': 'https://image.tmdb.org/t/p/original/rdMFjYYE0uZ55rBdlX149gRF1XQ.jpg',
    'Darkroom': 'https://image.tmdb.org/t/p/original/8G7qvHF7hdmXpfxxqtF1WT9ib68.jpg',
    'Channel 4 Plus': 'https://image.tmdb.org/t/p/original/trVzwZhFnxY3sCqyySnXASGBY9j.jpg',
    'Acaciatv Amazon Channel': 'https://image.tmdb.org/t/p/original/90uY3zG0NQzLvRlK6q2PhNggus5.jpg',
    'Adultswim Amazon Channel': 'https://image.tmdb.org/t/p/original/xLJyrRjQpP5xzWhXFCWlmHXnqTT.jpg',
    'Alchemiya Amazon Channel': 'https://image.tmdb.org/t/p/original/sRKgjbfea41FYrnLJ8fb3HxWHuW.jpg',
    'All warrior network Amazon Channel': 'https://image.tmdb.org/t/p/original/4FAHcgblW2K4bAQTOBgRjreSG5v.jpg',
    'Amebatv Amazon Channel': 'https://image.tmdb.org/t/p/original/o1MMI3qWdY78IWNSjqJz34db2sF.jpg',
    'Aspire TV Amazon Channel': 'https://image.tmdb.org/t/p/original/7ockkrlALB3USwd4SykWGXNOi2u.jpg',
    'BeFit Amazon Channel': 'https://image.tmdb.org/t/p/original/9L1RVS2dqMJAHfEWMZcWOsZuENc.jpg',
    'Best of British Tv Amazon Channel': 'https://image.tmdb.org/t/p/original/d4DhghomNx4W8eNZxiWBwYhTISn.jpg',
    'Baeble Amazon Channel': 'https://image.tmdb.org/t/p/original/oONBGuciYIr8QtZfK6DXEzyFla2.jpg',
    'Best Westerns Ever Amazon Channel': 'https://image.tmdb.org/t/p/original/zHcxRKfqUFsdG3taPDYGEu5E8FK.jpg',
    'Broadway HD Amazon Channel': 'https://image.tmdb.org/t/p/original/49xq9Js36idzOAbLPFLeKIaS8lz.jpg',
    'Brown Sugar Amazon Channel': 'https://image.tmdb.org/t/p/original/fAE2Y9TG1gkTB8xLAVm5WXIgjXw.jpg',
    'Cartoon Network Amazon Channel': 'https://image.tmdb.org/t/p/original/c4vuFkR7wof2vIeVhvaoo550ccE.jpg',
    'Jolt Film': 'https://image.tmdb.org/t/p/original/sBTV0rN8JUhF4G3uIceinWtQ3gi.jpg',
    'JioHotstar': 'https://image.tmdb.org/t/p/original/8b7I3EzWGQqi0Y1sJBmvQPf58Yd.jpg',
    'Filmelier Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/dMzlhtOV6znpyMMeHavtCkJzc5d.jpg',
    'Filmpalast Amazon Channel': 'https://image.tmdb.org/t/p/original/3MhtSwlhI03YD52q98pljG5oxZD.jpg',
    'Lionsgate+ Amazon Channels': 'https://image.tmdb.org/t/p/original/o4OqlMLb3ZjhK7OwR4qvxiZKOXf.jpg',
    'GEO Television + Wild Amazon Channel': 'https://image.tmdb.org/t/p/original/xc1sNY9m26IWTDLVch4l5RITE5n.jpg',
    'Polsat Box Go': 'https://image.tmdb.org/t/p/original/2YCt92ETw8xLXxhkURtMjZnzfKT.jpg',
    'Cinefest Amazon Channel': 'https://image.tmdb.org/t/p/original/wT06lfmmMFl1qUPSvyf3AikQThf.jpg',
    'CNN Max Amazon Channel': 'https://image.tmdb.org/t/p/original/323sW69J4GH2pYy7stNb9EqawhA.jpg',
    'The Coda Collection Amazon Channel': 'https://image.tmdb.org/t/p/original/3hMplVgqwHtta9UdJWSze18SgSk.jpg',
    'Midnight Pulp Amazon Channel': 'https://image.tmdb.org/t/p/original/ni2JXG9zznS4RYIGmeyBap1KwTD.jpg',
    'Daring Docs Amazon Channel': 'https://image.tmdb.org/t/p/original/sgWgoIcSqrFdRuteFcaYpd0iSOc.jpg',
    'Dekkoo Amazon Channel': 'https://image.tmdb.org/t/p/original/3mJLdi3mdSJr934KkyX2N8ZQOth.jpg',
    'DocCom Amazon Channel': 'https://image.tmdb.org/t/p/original/bHNDIVZWeq3Aq7y8qAhm2p3tVtg.jpg',
    'DocuramaFilms Amazon Channel': 'https://image.tmdb.org/t/p/original/7euDfXJ182rvLwRtZTjEhrEt0Z7.jpg',
    'Dove Amazon Channel': 'https://image.tmdb.org/t/p/original/i9GZoDffI29FmE7Y2Bk6hI6i0uR.jpg',
    'Dox Amazon Channel': 'https://image.tmdb.org/t/p/original/3P8zPlNET0zhg3UwJAj1I3MaPP8.jpg',
    'Philo': 'https://image.tmdb.org/t/p/original/ptmbGSttkyzawLbxx9MElmxKuVo.jpg',
    'Eagle No Limits Amazon Channel': 'https://image.tmdb.org/t/p/original/eWzA5sz5Qg9NGv6V5kUHmADjk0J.jpg',
    'Eagle Magic Amazon Channel': 'https://image.tmdb.org/t/p/original/7exnF8KeEZATJWogRA6XfZGhnl3.jpg',
    'Hidive Amazon Channel': 'https://image.tmdb.org/t/p/original/bpA0pUd1LqMJOPwdbUIdUPfP3gE.jpg',
    'Echoboom Amazon Channel ': 'https://image.tmdb.org/t/p/original/5fjo9JkLUHsyFmvSxNINObCgkGj.jpg',
    'Cocina ON Amazon Channel': 'https://image.tmdb.org/t/p/original/r2WsboLyjoNW3WgABuYwuiTGZqq.jpg',
    'Fear Factory Amazon Channel': 'https://image.tmdb.org/t/p/original/s1G5QtQxGzZGgNzqt3A78dMxz9z.jpg',
    'Film Movement Plus Amazon Channel': 'https://image.tmdb.org/t/p/original/cI2eH5SqS6RK5Vbo7YJsbDcr8Qa.jpg',
    'Fitfusion Amazon Channel': 'https://image.tmdb.org/t/p/original/63eFvx2SLvmGG2aYA4wrr4ofrBk.jpg',
    'Food Matters Amazon Channel': 'https://image.tmdb.org/t/p/original/zEzfWPUzj52e7UeBKZuRJnP394I.jpg',
    'France Channel Amazon Channel': 'https://image.tmdb.org/t/p/original/lXcldSz4TB0EiEcv4TqvzdUdEkG.jpg',
    'Fuse+ Amazon Channel': 'https://image.tmdb.org/t/p/original/lRGoPIT0vFf3xDJgp6sxfDNsxeP.jpg',
    'Hi-YAH Amazon Channel': 'https://image.tmdb.org/t/p/original/aysFX0644QGN9wQghp46qn08N0d.jpg',
    'Indie Club Amazon Channel': 'https://image.tmdb.org/t/p/original/A2fwubFtlBYXJtXAXMBcqNg646f.jpg',
    'IndieFlix Shorts Amazon Channel': 'https://image.tmdb.org/t/p/original/lerlw1kMpDQhfJqC0Z5T0ajCcpQ.jpg',
    'Here TV  Amazon Channel': 'https://image.tmdb.org/t/p/original/jIlFdRIvVEiwbDyigm6WbrLI3Lz.jpg',
};